source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'CoobjcDemo' do
    pod 'Masonry'
	pod 'AFNetworking'
	pod 'coobjc'

  target 'CoobjcDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoobjcDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
